{
    "error": {
        "http_code": 404,
        "message": "Кластер объектного хранилища не найден.",
        "traceback": [
            "Traceback (most recent call last):\n",
            "  File \"/usr/libexec/vstorage-ui-backend/venv/lib64/python3.4/site-packages/vstorage_ui_backend-1.3.185-py3.4.egg/backend/presentation/decorators.py\", line 28, in wrapper\n    return func(*args, **kwargs)\n",
            "  File \"/usr/libexec/vstorage-ui-backend/venv/lib64/python3.4/site-packages/vstorage_ui_backend-1.3.185-py3.4.egg/backend/presentation/s3/s3.py\", line 280, in post\n    create_release_nodes_service().release(cluster_id, **data)\n",
            "  File \"/usr/libexec/vstorage-ui-backend/venv/lib64/python3.4/site-packages/vstorage_ui_backend-1.3.185-py3.4.egg/backend/business/models/s3/release_node.py\", line 18, in release\n    rv = self._relaxed_release(storage_cluster_id, nodes)\n",
            "  File \"/usr/libexec/vstorage-ui-backend/venv/lib64/python3.4/site-packages/vstorage_ui_backend-1.3.185-py3.4.egg/backend/business/models/s3/release_node.py\", line 24, in _relaxed_release\n    s3_cluster, s3_nodes = self.validate_release_params(storage_cluster_id, nodes=nodes)\n",
            "  File \"/usr/libexec/vstorage-ui-backend/venv/lib64/python3.4/site-packages/vstorage_ui_backend-1.3.185-py3.4.egg/backend/business/models/s3/release_node.py\", line 97, in validate_release_params\n    s3_cluster = self.get_s3_cluster_by_storage_id(storage_cluster_id)\n",
            "  File \"/usr/libexec/vstorage-ui-backend/venv/lib64/python3.4/site-packages/vstorage_ui_backend-1.3.185-py3.4.egg/backend/business/models/s3/services.py\", line 42, in get_s3_cluster_by_storage_id\n    raise ObjectDoesNotExist(_('Object storage Cluster not found.'))\n",
            "backend.business.models.exceptions.ObjectDoesNotExist: Кластер объектного хранилища не найден.\n"
        ],
        "subsytem": "presentation",
        "errors": null
    },
    "message": "Кластер объектного хранилища не найден. (Deprecated field)"
}