{
    "error": {
        "http_code": 404,
        "message": "Cannot find S3 cluster for storage cluster",
        "traceback": [
            "Traceback (most recent call last):\n",
            "  File \"/usr/libexec/vstorage-ui-backend/venv/lib64/python3.4/site-packages/vstorage_ui_backend-1.3.185-py3.4.egg/backend/presentation/decorators.py\", line 28, in wrapper\n    return func(*args, **kwargs)\n",
            "  File \"/usr/libexec/vstorage-ui-backend/venv/lib64/python3.4/site-packages/vstorage_ui_backend-1.3.185-py3.4.egg/backend/presentation/s3/buckets.py\", line 29, in get\n    buckets, next_marker = create_s3_buckets_service(logger).scan_buckets(cluster_id, **params)\n",
            "  File \"/usr/libexec/vstorage-ui-backend/venv/lib64/python3.4/site-packages/vstorage_ui_backend-1.3.185-py3.4.egg/backend/business/models/s3/buckets/services.py\", line 17, in scan_buckets\n    chunk = self._buckets_dao.scan_buckets(storage_cluster_id, count, marker, prefix)\n",
            "  File \"/usr/libexec/vstorage-ui-backend/venv/lib64/python3.4/site-packages/vstorage_ui_backend-1.3.185-py3.4.egg/backend/business/models/s3/buckets/dao.py\", line 43, in scan_buckets\n    response = self._request(storage_cluster_id, query, notnone_dict(count=count, marker=marker, prefix=prefix))\n",
            "  File \"/usr/libexec/vstorage-ui-backend/venv/lib64/python3.4/site-packages/vstorage_ui_backend-1.3.185-py3.4.egg/backend/business/models/s3/buckets/dao.py\", line 24, in _request\n    raise ObjectDoesNotExist('Cannot find S3 cluster for storage cluster')\n",
            "backend.business.models.exceptions.ObjectDoesNotExist: Cannot find S3 cluster for storage cluster\n"
        ],
        "subsytem": "presentation",
        "errors": null
    },
    "message": "Cannot find S3 cluster for storage cluster (Deprecated field)"
}