{
    "error": {
        "http_code": 400,
        "message": "Incorrect json data",
        "traceback": [
            "Traceback (most recent call last):\n",
            "  File \"/usr/libexec/vstorage-ui-backend/venv/lib64/python3.4/site-packages/Flask-0.11.1-py3.4.egg/flask/wrappers.py\", line 156, in get_json\n    rv = json.loads(data)\n",
            "  File \"/usr/libexec/vstorage-ui-backend/venv/lib64/python3.4/site-packages/Flask-0.11.1-py3.4.egg/flask/json.py\", line 149, in loads\n    return _json.loads(s, **kwargs)\n",
            "  File \"/usr/libexec/vstorage-ui-backend/venv/lib64/python3.4/site-packages/simplejson-3.11.1-py3.4-linux-x86_64.egg/simplejson/__init__.py\", line 533, in loads\n    return cls(encoding=encoding, **kw).decode(s)\n",
            "  File \"/usr/libexec/vstorage-ui-backend/venv/lib64/python3.4/site-packages/simplejson-3.11.1-py3.4-linux-x86_64.egg/simplejson/decoder.py\", line 370, in decode\n    obj, end = self.raw_decode(s)\n",
            "  File \"/usr/libexec/vstorage-ui-backend/venv/lib64/python3.4/site-packages/simplejson-3.11.1-py3.4-linux-x86_64.egg/simplejson/decoder.py\", line 400, in raw_decode\n    return self.scan_once(s, idx=_w(s, idx).end())\n",
            "simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
            "\nDuring handling of the above exception, another exception occurred:\n\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/libexec/vstorage-ui-backend/venv/lib64/python3.4/site-packages/vstorage_ui_backend-1.3.185-py3.4.egg/backend/presentation/base.py\", line 99, in parse_payload\n    body = request.get_json()\n",
            "  File \"/usr/libexec/vstorage-ui-backend/venv/lib64/python3.4/site-packages/Flask-0.11.1-py3.4.egg/flask/wrappers.py\", line 161, in get_json\n    rv = self.on_json_loading_failed(e)\n",
            "  File \"/usr/libexec/vstorage-ui-backend/venv/lib64/python3.4/site-packages/Flask-0.11.1-py3.4.egg/flask/wrappers.py\", line 181, in on_json_loading_failed\n    raise BadRequest()\n",
            "werkzeug.exceptions.BadRequest: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.\n",
            "\nDuring handling of the above exception, another exception occurred:\n\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/libexec/vstorage-ui-backend/venv/lib64/python3.4/site-packages/vstorage_ui_backend-1.3.185-py3.4.egg/backend/presentation/decorators.py\", line 28, in wrapper\n    return func(*args, **kwargs)\n",
            "  File \"/usr/libexec/vstorage-ui-backend/venv/lib64/python3.4/site-packages/vstorage_ui_backend-1.3.185-py3.4.egg/backend/presentation/s3/s3.py\", line 246, in post\n    data = self.parse_post(AssignNodesParamsSchema)\n",
            "  File \"/usr/libexec/vstorage-ui-backend/venv/lib64/python3.4/site-packages/vstorage_ui_backend-1.3.185-py3.4.egg/backend/presentation/base.py\", line 101, in parse_payload\n    raise ValidationError('Incorrect json data')\n",
            "backend.business.models.exceptions.ValidationError: Incorrect json data\n"
        ],
        "subsytem": "presentation",
        "errors": null
    },
    "message": "Incorrect json data (Deprecated field)"
}